name: sus

on: 
  workflow_dispatch:
    inputs:
      what:
        description: 'it's morbin time'
        required: true
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run
      run: dotnet run ${{ secrets.TOKEN }}
